# Generated by Django 3.0.3 on 2020-03-08 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('customer_num', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('name_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_register.NameTitle')),
            ],
        ),
    ]
