# Generated by Django 3.0.3 on 2020-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0003_auto_20200309_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(help_text='Please enter your unique customer Id'),
        ),
    ]
